import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/structured-data";

/*
  robots.txt (generated by Next). Allow everything except the internal
  /specimen component gallery, and point crawlers at the sitemap.
*/
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/specimen", "/api/"],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
