import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/structured-data";

/*
  sitemap.xml (generated by Next). Lists the public, indexable routes only —
  the internal /specimen gallery is intentionally excluded (also blocked in
  robots.ts). When the /ro and /de locales go live, add their URLs here and
  wire `alternates.languages` for hreflang.
*/

// Case-study slugs, kept in one place so the list stays in sync with app/work/*.
const WORK_SLUGS = [
  "sws",
  "mnf",
  "taf",
  "lavabo",
  "crisp",
  "kabinett",
  "interstellar",
  "iwl",
  "kokop",
  "architrave",
] as const;

// Bumped when the site meaningfully changes; not per-request so builds stay
// deterministic.
const LAST_MODIFIED = "2026-07-23";

export default function sitemap(): MetadataRoute.Sitemap {
  const top: MetadataRoute.Sitemap = [
    { url: SITE_URL, changeFrequency: "monthly", priority: 1 },
    { url: `${SITE_URL}/work`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${SITE_URL}/contact`, changeFrequency: "yearly", priority: 0.7 },
  ];
  const work: MetadataRoute.Sitemap = WORK_SLUGS.map((slug) => ({
    url: `${SITE_URL}/work/${slug}`,
    changeFrequency: "yearly",
    priority: 0.8,
  }));
  return [...top, ...work].map((entry) => ({
    ...entry,
    lastModified: LAST_MODIFIED,
  }));
}
