import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/structured-data";
import { routing } from "@/i18n/routing";

/*
  sitemap.xml (generated by Next). One entry per (path × locale), each carrying
  hreflang `alternates.languages` linking all locales + x-default, so Google
  understands the EN/RO/DE versions. English is at the root (no prefix); RO/DE
  are under /ro, /de. The internal /specimen gallery stays out (also robots-
  blocked).
*/

const WORK_SLUGS = [
  "sws", "mnf", "taf", "lavabo", "crisp",
  "kabinett", "interstellar", "iwl", "kokop", "architrave",
] as const;

// Public, indexable paths (locale-agnostic).
const PATHS = ["", "/work", "/contact", ...WORK_SLUGS.map((s) => `/work/${s}`)];

// Bumped on meaningful changes; static so builds stay deterministic.
const LAST_MODIFIED = "2026-07-24";

function localizedUrl(locale: string, path: string) {
  const prefix = locale === routing.defaultLocale ? "" : `/${locale}`;
  return `${SITE_URL}${prefix}${path}`;
}

function priorityFor(path: string) {
  if (path === "") return 1;
  if (path === "/work") return 0.9;
  if (path.startsWith("/work/")) return 0.8;
  return 0.7; // /contact
}

export default function sitemap(): MetadataRoute.Sitemap {
  return PATHS.flatMap((path) => {
    const languages: Record<string, string> = {};
    for (const locale of routing.locales) {
      languages[locale] = localizedUrl(locale, path);
    }
    languages["x-default"] = localizedUrl(routing.defaultLocale, path);

    return routing.locales.map((locale) => ({
      url: localizedUrl(locale, path),
      lastModified: LAST_MODIFIED,
      changeFrequency: path === "" ? ("monthly" as const) : ("yearly" as const),
      priority: priorityFor(path),
      alternates: { languages },
    }));
  });
}
